# Generated by Django 5.1.2 on 2024-11-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_participante_remove_grupo_participante_grupo_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='participantes',
        ),
        migrations.AddField(
            model_name='participante',
            name='codigo_match',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.grupo'),
        ),
    ]
