# Generated by Django 5.1.2 on 2024-11-29 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_grupo_participantes_participante_codigo_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participante', to='main_app.grupo'),
        ),
    ]
